"""add utility_provider

Revision ID: 239ec2772177
Revises: 003_baseline_history
Create Date: 2026-02-03 12:46:08.737823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '239ec2772177'
down_revision: Union[str, None] = '003_baseline_history'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buildings', sa.Column('utility_provider', sa.String(), nullable=True))
    op.alter_column('buildings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_index('meter_readings_time_idx', table_name='meter_readings')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('meter_readings_time_idx', 'meter_readings', [sa.text('time DESC')], unique=False)
    op.alter_column('buildings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_column('buildings', 'utility_provider')
    # ### end Alembic commands ###
